
["Lotus Config"]
	#Mana each black lotus
	#How much mana should the black lotus give [8000]
	"Black Lotus Mana" = 8000
	#Mana each blacker lotus
	#How much mana should the blacker lotus give [100000]
	"Blacker Lotus Mana" = 100000

