
#General Settings
[general]
	#Default name visibility
	default_visible = false
	#Blocks hide nameplates. False is normal Minecraft nameplate rendering
	blocks_hide = false
	#Team color overrides individual player color
	team_override = true

